max_width = 80
tab_spaces = 4
indentation_style = "Spaces"
newline_style = "Auto"
attr_value_brace_style = "WhenRequired" # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
macro_names = [ "leptos::view", "view" ]
closing_tag_style = "SelfClosing"

[attr_values]
class = "Tailwind" # "Tailwind" is the only attribute value formatter available for now
